# -*- coding: utf-8 -*-
"""ALLE PLOT 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXbP6-YxMitMQmWIotGytUJiSir0-Br4
"""

import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
import warnings

# Skjul advarsler for at holde outputtet rent
warnings.filterwarnings('ignore')

# Opsætning af mapper
DATA_DIR = './sparc_data/'
OUTPUT_DIR = './spin_results/'

if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

# Hent alle datafiler
data_files = glob.glob(os.path.join(DATA_DIR, '*.dat'))
if len(data_files) == 0:
    print(f"Hov! Fandt ingen filer i {DATA_DIR}. Sørg for at uploade dem.")

# Mass-to-light ratios (Standard antagelser)
Y_disk = 0.5
Y_bul = 0.7

# Den nye stringent udledte SPIN-model
def spin_model(r, V_inf, L_e, r_data, V_bary_sq):
    # np.interp fungerer KUN rent, hvis r_data er sorteret (hvilket vi fikser længere nede)
    V_bary_sq_interp = np.interp(r, r_data, V_bary_sq)
    V_spin_sq = V_inf**2 * (r**2 / (r**2 + L_e**2))
    return np.sqrt(np.maximum(0, V_bary_sq_interp + V_spin_sq))

results_list = []
all_normalized_radii = []
all_residuals = []

print(f"Starter skudsikker analyse af {len(data_files)} galakser...")

for file_path in data_files:
    galaxy_name = os.path.basename(file_path).replace('.dat', '').replace('_rotmod', '')

    try:
        # FIX 1: Læs datafilen dynamisk. Brug comment='#' for at fjerne tekst-headers.
        # Vi lader pandas selv finde ud af afstanden (sep=r'\s+') mellem kolonnerne.
        df = pd.read_csv(file_path, sep=r'\s+', comment='#', header=None)

        # SPARC format er typisk: Rad, Vobs, errV, Vgas, Vdisk, Vbul.
        # Nogle galakser mangler bulge, så de har kun 5 kolonner.
        if df.shape[1] >= 6:
            df = df.iloc[:, 0:6] # Tag kun de første 6 kolonner for en sikkerheds skyld
            df.columns = ['Rad', 'Vobs', 'errV', 'Vgas', 'Vdisk', 'Vbul']
        elif df.shape[1] == 5:
            df.columns = ['Rad', 'Vobs', 'errV', 'Vgas', 'Vdisk']
            df['Vbul'] = 0.0 # Indsæt nuller, hvis der ikke er nogen bulge
        else:
            print(f"[{galaxy_name}] Skipper: Ukendt dataformat med {df.shape[1]} kolonner.")
            continue

        # Tving al data til at være tal (fjerner eventuelle tekst-fejl)
        df = df.apply(pd.to_numeric, errors='coerce').dropna()

        # FIX 2: SORTERING! Dette forhindrer "trappestigen" i at opstå.
        df = df.sort_values(by='Rad').reset_index(drop=True)

        if len(df) < 5:
            print(f"[{galaxy_name}] Skipper: For få datapunkter ({len(df)}).")
            continue

        # Beregn Baryonisk Hastighed
        V_gas_sq = df['Vgas'] * np.abs(df['Vgas'])
        V_disk_sq = Y_disk * df['Vdisk'] * np.abs(df['Vdisk'])
        V_bul_sq = Y_bul * df['Vbul'] * np.abs(df['Vbul'])

        V_bary_sq = V_gas_sq + V_disk_sq + V_bul_sq
        V_bary_sq[V_bary_sq < 0] = 0

        # Hent numpy arrays til fitting
        r_data = df['Rad'].values
        V_bary_sq_vals = V_bary_sq.values

        # Wrapper-funktion til curve_fit
        def fit_func(r, V_inf, L_e):
            return spin_model(r, V_inf, L_e, r_data, V_bary_sq_vals)

        # Udfør fittet (Rimelige fysiske grænser)
        p0 = [150.0, 5.0]
        bounds = ([10.0, 0.01], [500.0, 100.0])

        popt, pcov = curve_fit(fit_func, df['Rad'], df['Vobs'], sigma=df['errV'],
                               p0=p0, bounds=bounds, absolute_sigma=True)
        V_inf_opt, L_e_opt = popt

        # Beregn chi-squared og residualer
        predictions = fit_func(df['Rad'], V_inf_opt, L_e_opt)
        residuals = (df['Vobs'] - predictions) / df['errV']
        chi2 = np.sum(residuals**2)
        dof = len(df) - 2
        red_chi2 = chi2 / dof

        # Gem data
        results_list.append({
            'Galaxy': galaxy_name,
            'V_inf': V_inf_opt,
            'L_e': L_e_opt,
            'chi2_red': red_chi2
        })
        all_normalized_radii.extend(df['Rad'] / L_e_opt)
        all_residuals.extend(residuals)

        # ----- Lav individuelt plot -----
        r_smooth = np.linspace(df['Rad'].min(), df['Rad'].max() * 1.05, 200)
        V_tot_smooth = spin_model(r_smooth, V_inf_opt, L_e_opt, r_data, V_bary_sq_vals)
        V_spin_smooth = np.sqrt(V_inf_opt**2 * (r_smooth**2 / (r_smooth**2 + L_e_opt**2)))
        V_bary_smooth = np.sqrt(np.interp(r_smooth, r_data, V_bary_sq_vals))

        plt.figure(figsize=(9, 6))
        plt.errorbar(df['Rad'], df['Vobs'], yerr=df['errV'], fmt='ko', markersize=5, capsize=3, label='Data (SPARC)')
        plt.plot(r_smooth, V_tot_smooth, 'b-', linewidth=2.5, label='SPIN Total Fit')
        plt.plot(r_smooth, V_bary_smooth, 'g--', linewidth=1.5, label='Baryoner')
        plt.plot(r_smooth, V_spin_smooth, 'r:', linewidth=2, label='SPIN Halo')

        plt.title(f'{galaxy_name} | $\\chi^2_{{red}} = {red_chi2:.2f}$ | $V_\\infty = {V_inf_opt:.0f}$ km/s | $L_e = {L_e_opt:.1f}$ kpc', fontsize=14)
        plt.xlabel('Radius (kpc)', fontsize=12)
        plt.ylabel('Velocity (km/s)', fontsize=12)
        plt.legend(loc='lower right')
        plt.grid(alpha=0.3)
        plt.tight_layout()
        plt.savefig(f'{OUTPUT_DIR}/{galaxy_name}_spin_fit.png', dpi=150)
        plt.close()

    except Exception as e:
        print(f"[{galaxy_name}] Fejl under fitting: {e}")

# ----- Lav Master Plots -----
if len(results_list) > 0:
    results_df = pd.DataFrame(results_list)
    results_df.to_csv(f'{OUTPUT_DIR}/spin_all_results.csv', index=False)

    plt.figure(figsize=(8, 5))
    plt.hist(results_df['chi2_red'], bins=np.linspace(0, 5, 25), edgecolor='black', alpha=0.7)
    plt.axvline(results_df['chi2_red'].median(), color='r', linestyle='dashed', linewidth=2,
                label=f'Median $\\chi^2_{{red}}$ = {results_df["chi2_red"].median():.2f}')
    plt.title('Distribution of Reduced $\\chi^2$ (SPIN Model)', fontsize=14)
    plt.xlabel('Reduced $\\chi^2$', fontsize=12)
    plt.ylabel('Number of Galaxies', fontsize=12)
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/MASTER_chi2_histogram.png', dpi=200)
    plt.close()

    plt.figure(figsize=(10, 6))
    plt.scatter(all_normalized_radii, all_residuals, color='black', alpha=0.15, s=10)
    plt.axhline(0, color='r', linestyle='--')
    plt.axhline(2, color='gray', linestyle=':', alpha=0.5)
    plt.axhline(-2, color='gray', linestyle=':', alpha=0.5)
    plt.title('Universal Residuals for SPIN Formulation', fontsize=14)
    plt.xlabel('Normalized Radius ($r / L_e$)', fontsize=12)
    plt.ylabel('Residuals ($\\Delta V / \\sigma$)', fontsize=12)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(f'{OUTPUT_DIR}/MASTER_residuals_plot.png', dpi=200)
    plt.close()

    print(f"\n✅ Færdig! Analyserede med succes {len(results_df)} galakser.")
    print(f"📊 Median Chi-Squared: {results_df['chi2_red'].median():.2f}")